DROP TABLE IF EXISTS BUSINFORMATION;

CREATE TABLE BUSINFORMATION
(
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    BUSNUMBER     VARCHAR(10) NOT NULL,
    DIRECTIONCODE VARCHAR(1)  NOT NULL,
    BUSSTOPNUMBER VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS STOPINFORMATION;

CREATE TABLE STOPINFORMATION
(
    STOPID         INT PRIMARY KEY,
    STOPNAME       VARCHAR(50) NOT NULL,
    STOPAREANUMBER VARCHAR(20)  NOT NULL
);